name: Devevlop Branch Terraform Workflow

on:
  push:
    branches:
      - develop

jobs:
  execute-on-push:
    name: execute-on-push-test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "Esto debe de ejecutarse on develop branch"